version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: talkbox
  web:
    image: talkbox-server
    ports:
      - "3020:3020"
    networks:
      - webnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
networks:
  webnet:
